# Generated by Django 5.0.4 on 2024-11-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.CharField(choices=[('completed', 'Completed'), ('in_process', 'In Process'), ('pending', 'Pending')], default='pending', max_length=20)),
            ],
        ),
    ]
