# Generated by Django 5.0.4 on 2024-11-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easylunchapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
