# Generated by Django 5.1.3 on 2024-11-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easylunchapp', '0007_remove_order_products_orderproduct_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='customer_name', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='products_json',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
