# Generated by Django 5.1.3 on 2024-11-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easylunchapp', '0009_rename_name_product_product_name_alter_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products_json',
        ),
        migrations.AddField(
            model_name='order',
            name='products_with_quantities',
            field=models.JSONField(default=dict),
        ),
    ]
