# Generated by Django 5.1.3 on 2024-11-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easylunchapp', '0011_rename_products_with_quantities_order_product_quantities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_quantities',
            field=models.JSONField(default=list),
        ),
    ]
