# Generated by Django 5.1.3 on 2024-11-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easylunchapp', '0016_alter_order_customer_email_alter_order_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(default='customer_phone', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
