# Generated by Django 5.1.3 on 2024-11-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easylunchapp', '0017_remove_order_products_order_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.DateTimeField(default='2024-12-01T14:30:00'),
            preserve_default=False,
        ),
    ]
